/* What is pasted into Import is not always nftables.
 *
 * An `iptables-save` went straight through: every line to the prelude, no
 * error, a 100% round-trip ring, "0 rules", and a disabled button that said
 * nothing. Recognising the format is cheap and turns that into a sentence
 * naming the translator. */
import test from "node:test";
import assert from "node:assert/strict";
import { foreignFormat, translateCommand } from "../src/core/foreign.js";
import { SAMPLES } from "../src/core/samples.js";

const IPT4 = `# Generated by iptables-save v1.8.9 on Sat Aug 16 10:00:00 2026
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
COMMIT`;

test("an iptables-save is recognised, from any of its tell-tale lines", () => {
  assert.deepEqual(foreignFormat(IPT4), { kind: "iptables-save", v6: false });
  /* no header comment, no COMMIT — a fragment somebody copied from the middle */
  assert.equal(foreignFormat("-A INPUT -p tcp --dport 22 -j ACCEPT")?.kind, "iptables-save");
  assert.equal(foreignFormat("*nat\n:PREROUTING ACCEPT [0:0]")?.kind, "iptables-save");
});

test("ip6tables-save is told apart, so the translator named is the right one", () => {
  const v6 = IPT4.replace("iptables-save", "ip6tables-save").replace("--dport 22", "-s 2001:db8::/32 --dport 22");
  const f = foreignFormat(v6);
  assert.equal(f.kind, "iptables-save");
  assert.equal(f.v6, true);
  assert.equal(translateCommand(f), "ip6tables-restore-translate -f rules.v6");
  assert.equal(translateCommand(foreignFormat(IPT4)), "iptables-restore-translate -f rules.v4");
});

test("the JSON that nft -j prints is recognised as the other door", () => {
  assert.equal(foreignFormat('{"nftables": [{"metainfo": {"version": "1.1.6"}}]}')?.kind, "nft-json");
});

test("every nftables sample is not foreign, and neither is nothing", () => {
  for (const s of SAMPLES) assert.equal(foreignFormat(s.text), null, s.id);
  assert.equal(foreignFormat(""), null);
  assert.equal(foreignFormat("   \n"), null);
  /* the words inside a comment or a string are not a format */
  assert.equal(foreignFormat('table inet t {\n\tchain c {\n\t\ttcp dport 22 accept comment "COMMIT -A INPUT"\n\t}\n}'), null);
});
