/* What the import dialog says about text that is not nftables.
 *
 * An `iptables-save` pasted here produced the worst possible first minute for
 * the people this is for: every line went into the prelude as kept text, the
 * parser reported no error, the ring read 100% with "nothing was lost", the
 * count read "0 rules", and the Import button sat disabled without a word
 * about why. The product looked as if it was lying. It names the format now,
 * and the translator that turns it into what this dialog reads.
 *
 * The strings asserted are the ones that read the same in both languages —
 * the interface boots in Spanish by default — plus an either-language check
 * where the sentence differs. */
import test, { after } from "node:test";
import assert from "node:assert/strict";
import { boot, shutdown, $, settle, text } from "./harness.js";

after(shutdown);

const IPT4 = `# Generated by iptables-save v1.8.9 on Sat Aug 16 10:00:00 2026
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
COMMIT`;

const paste = async (s) => {
  const a = $("#imp-text");
  a.value = s;
  a.dispatchEvent(new globalThis.window.Event("input", { bubbles: true }));
  await settle(40);
};

test("an iptables-save pasted into Import is named, and the translator with it", async () => {
  await boot();
  await paste(IPT4);
  const side = text("#imp-side");
  assert.equal($("#imp-go").disabled, true, "there is nothing to import");
  assert.match(side, /iptables-save/, "the format is named");
  assert.match(side, /iptables-restore-translate -f rules\.v4/, "and so is the command that translates it");
  assert.doesNotMatch(side, /100%|Nothing was lost|No se ha perdido nada/,
    "no green ring over zero rules");
});

test("ip6tables-save gets the v6 translator", async () => {
  await boot();
  await paste(IPT4.replace("iptables-save", "ip6tables-save").replace("--dport 22", "-s 2001:db8::/32 --dport 22"));
  assert.match(text("#imp-side"), /ip6tables-restore-translate -f rules\.v6/);
});

/* A define and an include come back 100% and are still nothing to import. */
test("lines that are all kept and none of them a rule do not claim nothing was lost", async () => {
  await boot();
  await paste('define wan = "eth0"\ninclude "/etc/nftables.d/*.nft"');
  const side = text("#imp-side");
  assert.equal($("#imp-go").disabled, true);
  assert.match(side, /nothing to import|nada que importar/);
  assert.doesNotMatch(side, /Nothing was lost|No se ha perdido nada/);
});

/* And a real ruleset still gets the ring it earned. */
test("a ruleset with rules is not mistaken for a foreign format", async () => {
  await boot();
  await paste(`table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		tcp dport 22 accept comment "COMMIT is just a word here"
	}
}`);
  assert.equal($("#imp-go").disabled, false);
  assert.doesNotMatch(text("#imp-side"), /iptables/);
  assert.match(text("#imp-side"), /100%/);
});
