/* Rulesets that are not nftables, recognised before anything is parsed.
 *
 * Pasting an `iptables-save` into the import dialog used to produce the worst
 * possible first minute: every line went into the prelude as text nobody
 * understood, so the parser reported nothing wrong, the round-trip ring showed
 * 100% with "nothing was lost", the count read "0 rules", and the Import
 * button stayed disabled with no word about why. Half of the people this is
 * for are still on iptables, and that is the first thing they will paste.
 *
 * Nothing here parses either format. It only says what the text is, so the
 * dialog can say so too — and name the tool that translates it. */

/* iptables-save / ip6tables-save: table headers, chain declarations with a
   policy and counters, `-A CHAIN …` rules, and COMMIT — any one of those on a
   line of its own is not something nftables syntax ever produces. */
const IPT = [
  /^\*(filter|nat|mangle|raw|security)\s*$/m,
  /^:[A-Za-z0-9_-]+\s+(ACCEPT|DROP|-)\s+\[\d+:\d+\]/m,
  /^-[AI]\s+[A-Za-z0-9_-]+\s/m,
  /^COMMIT\s*$/m,
  /^# Generated by (ip6?tables-save|xtables-save|iptables-legacy-save)/m,
];

export function foreignFormat(text){
  const s = String(text || "");
  if(!s.trim()) return null;

  if(IPT.some(re => re.test(s))){
    /* ip6tables-save looks identical apart from the addresses and the header */
    const v6 = /^# Generated by ip6tables/m.test(s) || /^-A\s+\S+.*\s(?:-s|-d)\s+[0-9a-f:]*:[0-9a-f:/]*/mi.test(s);
    return { kind: "iptables-save", v6 };
  }

  /* `nft -j list ruleset` — the JSON form. A different door, not this one. */
  const head = s.trimStart();
  if(head.startsWith("{") && /"nftables"\s*:/.test(head.slice(0, 200)))
    return { kind: "nft-json", v6: false };

  return null;
}

/* The command that turns it into what this dialog reads. Both translators ship
   with the nft-based iptables (the `iptables` package on Debian and Fedora). */
export const translateCommand = (f) =>
  f?.kind === "iptables-save"
    ? (f.v6 ? "ip6tables-restore-translate -f rules.v6" : "iptables-restore-translate -f rules.v4")
    : f?.kind === "nft-json" ? "nft list ruleset" : "";
