/* Model → nftables source. Tables are discovered, never assumed.
 *
 * Emission also records where each line came from. Without that, the code pane
 * has to match rules back to lines by their text — and two chains can hold the
 * same rule, so selecting one would highlight all of them. Provenance makes
 * the round-trip identity-based instead of string-based.
 *
 * The output is shaped the way `nft list ruleset` shapes it — one attribute
 * per line, `priority filter;` rather than `priority 0 ;` — so that a ruleset
 * read off a host and written back out compares line for line. That is what
 * makes verify() in parse.js able to make a claim about the whole file rather
 * than only about its rules. */
import { MODEL, ruleLine, UID } from "./model.js";
import { PROJECT } from "./project.js";

/* The set body, in the order it was read. `type`, `flags` and `elements` are
   the parts the editor owns and are re-emitted from the live values; anything
   else — size, timeout, gc-interval, auto-merge, policy, comment — is put back
   exactly where it sat. A set built in the editor has no recorded body, so it
   gets the canonical one. */
function setBody(s){
  const body = s.body?.length ? s.body : [{ k: "type" }, { k: "flags" }, { k: "elements" }];
  const seen = new Set(body.map(x => x.k));
  const out = [];
  for(const slot of body){
    let line = null;
    if(slot.k === "type")     line = `${s.decl || "type"} ${s.t}`;
    else if(slot.k === "flags"){ if(s.f) line = `flags ${s.f}`; }
    else if(slot.k === "attr")  line = attrLine(s, slot.n);
    else if(slot.k === "elements"){ if(s.el.length) line = `elements = { ${s.el.join(", ")} }`; }
    else line = slot.v;
    if(line === null) continue;
    /* it arrived sharing a line with the statement before it, separated by the
       `;` that nft puts between statements — put it back where it was */
    if(slot.join && out.length) out[out.length - 1] += ` ; ${line}`;
    else out.push(line);
  }
  /* flags, attributes or elements added in the editor to a set read without
     them; nft wants them all before the elements */
  if(s.f && !seen.has("flags")) out.splice(1, 0, `flags ${s.f}`);
  const had = new Set(body.filter(x => x.k === "attr").map(x => x.n));
  const at = out.findIndex(l => l.startsWith("elements"));
  for(const n of Object.keys(s.attr || {})){
    if(had.has(n)) continue;
    const line = attrLine(s, n);
    if(line === null) continue;
    if(at >= 0) out.splice(at, 0, line); else out.push(line);
  }
  if(s.el.length && !seen.has("elements")) out.push(`elements = { ${s.el.join(", ")} }`);
  return out;
}

/* `auto-merge` is a flag with no value; the rest carry one. Either way an
   attribute the editor has cleared is an attribute that is not emitted. */
function attrLine(s, n){
  const v = s.attr?.[n];
  if(v === undefined || v === null || v === "" || v === false) return null;
  return n === "auto-merge" ? "auto-merge" : `${n} ${v}`;
}

/**
 * @param model  chains, sets, objects and tables
 * @param opts.scope
 *   "ruleset" — `flush ruleset` first. Replaces everything the kernel holds,
 *               which is right for a machine that runs only this ruleset.
 *   "tables"  — replace the tables this project owns and leave the rest. Most
 *               machines also run Docker, libvirt, kubernetes or fail2ban, and
 *               every one of those keeps its rules in a table of its own that
 *               `flush ruleset` deletes without telling anybody.
 */
export function generateWithMap(model = MODEL, opts = {}) {
  const scope = opts.scope === "tables" ? "tables" : "ruleset";
  const chains = model.chains || [];
  const sets = model.sets || [];
  const objects = model.objects || [];
  const tableInfo = model.tables || [];

  const L = [];
  const M = []; // parallel to L: {uid, i} for rule lines, null otherwise
  const put = (line, origin = null) => {
    L.push(line);
    M.push(origin);
  };

  put("#!/usr/sbin/nft -f");
  put(`# ${PROJECT()} — generated by eFeFlow · round-trip safe`);
  put("");

  const tables = [
    ...new Set([
      ...chains.map((c) => c.table),
      ...sets.map((s) => s.table).filter(Boolean),
      ...objects.map((o) => o.table).filter(Boolean),
      ...tableInfo.map((t) => t.name),
    ]),
  ];
  if (!tables.length) tables.push("inet fw");

  if (scope === "ruleset") {
    put("flush ruleset");
    put("");
  } else {
    /* create-then-delete-then-create: a bare `table X` is a no-op when it
       exists and creates it when it does not, so the delete after it never
       fails on a host that has never seen this table. */
    put("# replaces only the tables below — anything else on the host is left alone");
    tables.forEach((tb) => {
      put(`table ${tb}`);
      put(`delete table ${tb}`);
    });
    put("");
  }

  tables.forEach((tb) => {
    put(`table ${tb} {`);

    /* table-level statements: `flags dormant`, `comment "…"`. Losing the first
       turns a firewall its author had deliberately parked back on. */
    const info = tableInfo.find((t) => t.name === tb);
    if (info?.extra.length) {
      info.extra.forEach((l) => put(`\t${l}`));
      put("");
    }

    /* a set with no recorded table belongs to the first one, as nft requires
       it to live beside the rules that reference it */
    sets
      .filter((s) => (s.table || tables[0]) === tb)
      .forEach((s) => {
        put(`\t${s.kind === "map" ? "map" : "set"} ${s.n} {`);
        setBody(s).forEach((l) => put(`\t\t${l}`));
        put("\t}");
        put("");
      });

    /* flowtables, named counters and quotas, ct helpers and timeouts: the
       objects nftables has and this model does not, kept as they arrived */
    objects
      .filter((o) => o.table === tb)
      .forEach((o) => {
        put(`\t${o.kind}${o.name ? " " + o.name : ""} {`);
        o.body.forEach((l) => put(`\t\t${l}`));
        put("\t}");
        put("");
      });

    chains
      .filter((c) => c.table === tb)
      .forEach((ch) => {
        put(`\tchain ${ch.id} {`);
        if (ch.hook) {
          /* nft prints known priorities by name, so a `priority dstnat` that
             comes back as `priority -100` is a diff on every chain header */
          const prio = ch.prioName || ch.prio;
          const dev = ch.dev ? ch.dev + " " : "";
          put(`\t\ttype ${ch.type} hook ${ch.hook} ${dev}priority ${prio}; policy ${ch.policy};`);
        }
        (ch.extra || []).forEach((l) => put(`\t\t${l}`));
        ch.rules.forEach((r, i) => {
          if (!r.on) return;
          put(`\t\t${ruleLine(r)}${r.cmt ? ` comment "${r.cmt}"` : ""}`, { uid: UID(ch), i });
        });
        put("\t}");
        put("");
      });

    if (L.at(-1) === "") {
      L.pop();
      M.pop();
    }
    put("}");
    put("");
  });

  if (L.at(-1) === "") {
    L.pop();
    M.pop();
  }
  return { lines: L, map: M };
}

export const generate = (model, opts) => generateWithMap(model, opts).lines;
