/* Model → nftables source. Tables are discovered, never assumed.
 *
 * Emission also records where each line came from. Without that, the code pane
 * has to match rules back to lines by their text — and two chains can hold the
 * same rule, so selecting one would highlight all of them. Provenance makes
 * the round-trip identity-based instead of string-based.
 *
 * The output is shaped the way `nft list ruleset` shapes it — one attribute
 * per line, `priority filter;` rather than `priority 0 ;` — so that a ruleset
 * read off a host and written back out compares line for line. That is what
 * makes verify() in parse.js able to make a claim about the whole file rather
 * than only about its rules. */
import { MODEL, ruleLine, UID, cmtEsc } from "./model.js";
import { PROJECT } from "./project.js";

/* The set body, in the order it was read. `type`, `flags` and `elements` are
   the parts the editor owns and are re-emitted from the live values; anything
   else — size, timeout, gc-interval, auto-merge, policy, comment — is put back
   exactly where it sat. A set built in the editor has no recorded body, so it
   gets the canonical one. */
function setBody(s){
  const body = s.body?.length ? s.body : [{ k: "type" }, { k: "flags" }, { k: "elements" }];
  const seen = new Set(body.map(x => x.k));
  const out = [];
  for(const slot of body){
    let line = null;
    if(slot.k === "type")     line = `${s.decl || "type"} ${s.t}`;
    else if(slot.k === "flags"){ if(s.f) line = `flags ${s.f}`; }
    else if(slot.k === "attr")  line = attrLine(s, slot.n);
    else if(slot.k === "elements"){ if(s.el.length) line = `elements = { ${s.el.join(", ")} }`; }
    else line = slot.v;
    if(line === null) continue;
    /* it arrived sharing a line with the statement before it, separated by the
       `;` that nft puts between statements — put it back where it was */
    if(slot.join && out.length) out[out.length - 1] += ` ; ${line}`;
    else out.push(line);
  }
  /* flags, attributes or elements added in the editor to a set read without
     them; nft wants them all before the elements */
  if(s.f && !seen.has("flags")) out.splice(1, 0, `flags ${s.f}`);
  const had = new Set(body.filter(x => x.k === "attr").map(x => x.n));
  const at = out.findIndex(l => l.startsWith("elements"));
  for(const n of Object.keys(s.attr || {})){
    if(had.has(n)) continue;
    const line = attrLine(s, n);
    if(line === null) continue;
    if(at >= 0) out.splice(at, 0, line); else out.push(line);
  }
  if(s.el.length && !seen.has("elements")) out.push(`elements = { ${s.el.join(", ")} }`);
  return out;
}

/* `auto-merge` is a flag with no value; the rest carry one. Either way an
   attribute the editor has cleared is an attribute that is not emitted. */
function attrLine(s, n){
  const v = s.attr?.[n];
  if(v === undefined || v === null || v === "" || v === false) return null;
  return n === "auto-merge" ? "auto-merge" : `${n} ${v}`;
}

/**
 * @param model  chains, sets, objects and tables
 * @param opts.scope
 *   "ruleset" — `flush ruleset` first. Replaces everything the kernel holds,
 *               which is right for a machine that runs only this ruleset.
 *   "tables"  — replace the tables this project owns and leave the rest. Most
 *               machines also run Docker, libvirt, kubernetes or fail2ban, and
 *               every one of those keeps its rules in a table of its own that
 *               `flush ruleset` deletes without telling anybody.
 */
export function generateWithMap(model = MODEL, opts = {}) {
  const scope = opts.scope === "tables" ? "tables" : "ruleset";
  const chains = model.chains || [];
  const sets = model.sets || [];
  const objects = model.objects || [];
  const tableInfo = model.tables || [];

  const L = [];
  const M = []; // parallel to L: {uid, i} for rule lines, null otherwise
  const put = (line, origin = null) => {
    L.push(line);
    M.push(origin);
  };

  put("#!/usr/sbin/nft -f");
  put(`# ${PROJECT()} — generated by eFeFlow · round-trip safe`);
  put("");

  /* `define wan = "eth0"` and the includes, above the first table because a
     definition after its use is not a definition. These were dropped while
     the rules using `$wan` were kept, so an imported script came back out
     referencing a variable nothing defined. */
  /* A prelude line goes back where it was: `preludeAt[i]` is how many tables
     were declared above it. Group 0 is written here, above every table, and the
     rest follow the table they were written after — see the note in parse.js
     for why moving them is not a cosmetic matter. */
  const preludeAt = model.preludeAt || [];
  const preludeGroup = (k) => (model.prelude || [])
    .filter((_, i) => (preludeAt[i] || 0) === k);
  const preludeFrom = (k) => (model.prelude || [])
    .filter((_, i) => (preludeAt[i] || 0) >= k);

  if (preludeGroup(0).length) {
    /* `flush table inet x` fails on a table that is not there, and the whole
       file goes with it: "No such file or directory; did you mean table 'x' in
       family inet?" The idiom people write is three lines —
     *
     *     table inet x { }          create it if it is not there
     *     flush table inet x        now it exists, so this cannot fail
     *     table inet x { … }        and here is what it holds
     *
     * and the prelude keeps the flush while the empty declaration above it has
     * nowhere to live, because everything here is emitted before any table.
     * Rather than dropping somebody's line — preserve by default is the rule
     * of this file — the line that makes it work is written back with it. nft
     * takes a bare `table inet x` as create-if-absent, which is what the empty
     * block was for. Three of the four rulesets we emitted unloadably were
     * this one shape. */
    const created = new Set();
    for (const l of preludeGroup(0)) {
      const f = l.match(/^flush\s+table\s+(?:(\S+)\s+)?(\S+)\s*$/);
      if (f) {
        const decl = `table ${f[1] ? f[1] + " " : ""}${f[2]}`;
        if (!created.has(decl)) { put(decl); created.add(decl); }
      }
      const d = l.match(/^table\s+(?:\S+\s+)?\S+\s*$/);
      if (d) created.add(l.trim());
      put(l);
    }
    put("");
  }

  /* In the order the file declared them, which is `tableInfo` — the parser
     records one entry per table as it closes. Deriving the order from the
     members instead put every table that has none at the end, because it is
     only named by its own declaration: `table ip t3 { }` between two full
     tables came out after both of them, and `nft list ruleset` prints tables in
     the order they were created, so the two listings differed. Three of the four
     rulesets whose meaning the kernel said had moved were this and nothing else.
   *
   * Then anything named only by a member, which is how a table made in the
   * editor arrives — there is no declaration for it to have recorded. */
  const tables = [
    ...new Set([
      ...tableInfo.map((t) => t.name),
      ...chains.map((c) => c.table),
      ...sets.map((s) => s.table).filter(Boolean),
      ...objects.map((o) => o.table).filter(Boolean),
    ]),
  ];
  if (!tables.length) tables.push("inet fw");

  if (scope === "ruleset") {
    put("flush ruleset");
    put("");
  } else {
    /* create-then-delete-then-create: a bare `table X` is a no-op when it
       exists and creates it when it does not, so the delete after it never
       fails on a host that has never seen this table. */
    put("# replaces only the tables below — anything else on the host is left alone");
    tables.forEach((tb) => {
      put(`table ${tb}`);
      put(`delete table ${tb}`);
    });
    put("");
  }

  tables.forEach((tb, ti) => {
    put(`table ${tb} {`);

    /* table-level statements: `flags dormant`, `comment "…"`. Losing the first
       turns a firewall its author had deliberately parked back on.
     *
     * All of it at the top, including what nft never prints because it was never
     * in the kernel to print: a `define` scoped to this table, and an `include`
     * of the files that belong to it. One corpus ruleset writes its include as
     * the last line inside the table and gets it back as the first, which is one
     * line of one file in three thousand — and moving them to the bottom to fix
     * that put every table-scoped `define` below the rules that use it, which is
     * a file that does not load. There is no nft answer to appeal to here, since
     * nft has nothing to say about a line it never sees, so the safe order wins. */
    const info = tableInfo.find((t) => t.name === tb);
    if (info?.extra.length) {
      info.extra.forEach((l) => put(`\t${l}`));
      put("");
    }

    /* What order the members of a table come out in.
     *
     * This emitted sets, then objects, then chains. nft prints named objects
     * *first* — counter, quota, set, chain, checked against nft 1.1.6 — so any
     * ruleset with a named counter or a flowtable came back out reordered, and
     * the round-trip check read the move as loss. It reported 85% on a file
     * nothing had been dropped from, which is the one number this application
     * asks people to trust.
     *
     * So members keep the position they arrived in, and anything made since —
     * which has no position — follows in nft's own order. A set with no
     * recorded table belongs to the first one, as nft requires it to live
     * beside the rules that reference it. Declaration order does not matter to
     * nft itself: a chain may name a set declared below it, also checked. */
    const RANK = { object: 0, set: 1, chain: 2 };
    const members = [
      ...objects.filter((o) => o.table === tb).map((o) => ({ o, at: o.seq, k: "object" })),
      ...sets.filter((s) => (s.table || tables[0]) === tb).map((s) => ({ s, at: s.seq, k: "set" })),
      ...chains.filter((c) => c.table === tb).map((c) => ({ c, at: c.seq, k: "chain" })),
    ].sort((a, b) => {
      const known = (x) => typeof x.at === "number";
      if (known(a) && known(b)) return a.at - b.at;
      if (known(a) !== known(b)) return known(a) ? -1 : 1;   /* imported first */
      return RANK[a.k] - RANK[b.k];                          /* then nft's order */
    });

    members.forEach((m) => {
      if (m.k === "object") {
        const o = m.o;
        put(`\t${o.kind}${o.name ? " " + o.name : ""} {`);
        /* An object body can hold a block of its own — a `tunnel` has a
           `geneve { … }` in it — so the indentation follows the braces rather
           than being one fixed depth. Cosmetic to nft and not to a person
           reading it. */
        let deep = 2;
        o.body.forEach((l) => {
          if (/^\}/.test(l)) deep--;
          put("\t".repeat(Math.max(2, deep)) + l);
          if (/\{$/.test(l)) deep++;
        });
      } else if (m.k === "set") {
        const s = m.s;
        put(`\t${s.kind === "map" ? "map" : "set"} ${s.n} {`);
        setBody(s).forEach((l) => put(`\t\t${l}`));
      } else {
        const ch = m.c;
        put(`\tchain ${ch.id} {`);
        /* A chain's comment goes above its header, because that is where nft
           itself prints it — asked of nft 1.1.6 rather than assumed. Thirty-three
           chains across the corpus were written that way and came back with the
           comment underneath, which is the round-trip check reporting a line as
           lost and then found for no reason at all. Everything else a chain
           carries stays below the header, where nft puts it. */
        const extra = ch.extra || [];
        extra.filter((l) => /^comment\s/.test(l)).forEach((l) => put(`\t\t${l}`));
        if (ch.hook) {
          /* nft prints known priorities by name, so a `priority dstnat` that
             comes back as `priority -100` is a diff on every chain header */
          const prio = ch.prioName || ch.prio;
          const dev = ch.dev ? ch.dev + " " : "";
          put(`\t\ttype ${ch.type} hook ${ch.hook} ${dev}priority ${prio}; policy ${ch.policy};`);
        }
        extra.filter((l) => !/^comment\s/.test(l)).forEach((l) => put(`\t\t${l}`));
        ch.rules.forEach((r, i) => {
          if (!r.on) return;
          put(`\t\t${ruleLine(r)}${r.cmt ? ` comment "${cmtEsc(r.cmt)}"` : ""}`, { uid: UID(ch), i });
        });
      }
      put("\t}");
      put("");
    });

    if (L.at(-1) === "") {
      L.pop();
      M.pop();
    }
    put("}");
    put("");

    /* the prelude lines written after this table — and after the last table,
       everything that was left, so a line whose table has since been deleted in
       the editor is still written rather than dropped */
    const after = ti === tables.length - 1 ? preludeFrom(ti + 1) : preludeGroup(ti + 1);
    if (after.length) {
      after.forEach((l) => put(l));
      put("");
    }
  });

  if (L.at(-1) === "") {
    L.pop();
    M.pop();
  }
  return { lines: L, map: M };
}

export const generate = (model, opts) => generateWithMap(model, opts).lines;
